include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - test/**/*.g.dart
  errors:
    argument_type_not_assignable: warning
    non_bool_condition: warning
    always_declare_return_types: warning
    constant_identifier_names: info
    always_specify_types: info
    lines_longer_than_80_chars: info
    library_names: info
    avoid_empty_else: info
    unnecessary_parenthesis: info
    unnecessary_this: info
    empty_statements: warning
    unnecessary_const: info
    unnecessary_overrides: warning
    unnecessary_brace_in_string_interps: info
    prefer_final_locals: info
    prefer_final_in_for_each: info
    prefer_final_fields: info
    #    unawaited_futures: warning
    sort_child_properties_last: info
    #  require_trailing_commas: info
    prefer_null_aware_operators: info
    prefer_iterable_whereType: info
    prefer_is_not_operator: info
    prefer_is_empty: info
    prefer_is_not_empty: info
    prefer_interpolation_to_compose_strings: info
    prefer_initializing_formals: info
    prefer_if_null_operators: info
    prefer_if_elements_to_conditional_expressions: info
    prefer_foreach: info
    prefer_expression_function_bodies: info
    prefer_contains: info
    prefer_const_declarations: info
    prefer_const_constructors: info
    prefer_conditional_assignment: info
    only_throw_errors: warning
    empty_constructor_bodies: info
    avoid_void_async: error
    avoid_unused_constructor_parameters: info
    avoid_unnecessary_containers: info
    avoid_positional_boolean_parameters: warning
    always_use_package_imports: warning
    avoid_relative_lib_imports: warning

linter:
  rules:
    use_string_in_part_of_directives: false
    constant_identifier_names: false
    always_specify_types: true
    lines_longer_than_80_chars: true
    library_names: true
    avoid_empty_else: true
    unnecessary_parenthesis: true
    unnecessary_this: true
    empty_statements: true
    unnecessary_const: true
    unnecessary_overrides: true
    unnecessary_brace_in_string_interps: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_final_fields: true
    #    unawaited_futures: true
    sort_child_properties_last: true
    #    require_trailing_commas: true
    prefer_null_aware_operators: true
    prefer_iterable_whereType: true
    prefer_is_not_operator: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_interpolation_to_compose_strings: true
    prefer_initializing_formals: true
    prefer_if_null_operators: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_foreach: true
    prefer_expression_function_bodies: true
    prefer_contains: true
    prefer_const_declarations: true
    prefer_const_constructors: true
    prefer_conditional_assignment: true
    only_throw_errors: true
    empty_constructor_bodies: true
    avoid_void_async: true
    avoid_unused_constructor_parameters: true
    avoid_unnecessary_containers: true
    avoid_positional_boolean_parameters: true
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    always_declare_return_types: true