name: mafia_game
description: This project is for social deduction party game Mafia.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+9

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  styled_widget: ^0.4.1
  google_fonts: 6.1.0
  dropdown_button2: ^2.3.9
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  wolt_modal_sheet: ^0.4.1
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  path: ^1.8.3
  image_picker: ^1.0.7
  aligned_dialog: ^0.0.7
  audioplayers: ^5.2.1
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  flutter_ringtone_player: ^4.0.0+2
  intl: ^0.19.0
  avatar_glow: ^3.0.1
  introduction_screen: ^3.1.6
  flutter_typeahead: ^5.2.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.0
  accordion: ^2.6.0
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_m.png"
  min_sdk_android: 21

dependency_overrides:
  intl: ^0.18.1

  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/
    - assets/sounds/clock2.wav

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
