// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_BugVMuqwdunCG8bVsg68m4ONTQa177U',
    appId: '1:825669646140:web:ca11fdd7743506871f9039',
    messagingSenderId: '825669646140',
    projectId: 'acoustic-rider-349511',
    authDomain: 'acoustic-rider-349511.firebaseapp.com',
    databaseURL: 'https://acoustic-rider-349511-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'acoustic-rider-349511.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqlFQNHr80SLYP_MpQsZPV6WuQtHT3z1Q',
    appId: '1:825669646140:android:cf0c103133b5b85c1f9039',
    messagingSenderId: '825669646140',
    projectId: 'acoustic-rider-349511',
    databaseURL: 'https://acoustic-rider-349511-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'acoustic-rider-349511.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLVq-Fs90eiGYOFGW2JctYx_6L3YHPVSA',
    appId: '1:825669646140:ios:da4cbab91c44f8641f9039',
    messagingSenderId: '825669646140',
    projectId: 'acoustic-rider-349511',
    databaseURL: 'https://acoustic-rider-349511-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'acoustic-rider-349511.appspot.com',
    iosBundleId: 'com.example.mafiaGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLVq-Fs90eiGYOFGW2JctYx_6L3YHPVSA',
    appId: '1:825669646140:ios:d93118d79fa132d61f9039',
    messagingSenderId: '825669646140',
    projectId: 'acoustic-rider-349511',
    databaseURL: 'https://acoustic-rider-349511-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'acoustic-rider-349511.appspot.com',
    iosBundleId: 'com.example.mafiaGame.RunnerTests',
  );
}
